### ISSUE TITLE
ImportError: cannot import name 'Cart'

### ISSUE THREAD

**Issue by cqcallaw** [bmentges/django-cart#23]
Running Python 3.4.3 and Django 1.9.5 (inside a `virtualenv` environment), I get the following error when running `python manage.py makemigrations` (I'm not using South):

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/caleb/projects/dev/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/caleb/projects/dev/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/caleb/projects/dev/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/caleb/projects/dev/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/caleb/projects/dev/lib/python3.4/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/caleb/projects/dev/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/caleb/projects/dev/lib/python3.4/site-packages/cart/__init__.py", line 1, in <module>
    from cart import Cart, ItemAlreadyExists, ItemDoesNotExist
ImportError: cannot import name 'Cart'
```
The INSTALLED_APPS section of `settings.py` looks like this:

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart',
]
```

django-cart was installed via `pip install django-cart`

**Comment by qmarlats** [comment]
The same for me

**Comment by caroso1222** [comment]
This is happening because you're not importing it correctly on your .py file. README.md states you should import it like this `from cart import Cart`. This is why it breaks. You should explicitly define which file are you importing your class form. So you should import it this way:

`from cart.cart import Cart`

**Comment by bmentges** [comment]
Fixed in the README! Thanks for pointing it out @caroso1222 !
