### ISSUE TITLE
am getting the following error when trying to migrate

### ISSUE THREAD

**Issue by rickmutua** [bmentges/django-cart#32]
(virtual) erick@rick:~/Documents/personal projects/gift a box$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/erick/Documents/personal projects/gift a box/virtual/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/erick/Documents/personal projects/gift a box/virtual/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/erick/Documents/personal projects/gift a box/virtual/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/erick/Documents/personal projects/gift a box/virtual/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/erick/Documents/personal projects/gift a box/virtual/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/erick/Documents/personal projects/gift a box/virtual/lib/python3.6/site-packages/cart/models.py", line 26, in <module>
    class Item(models.Model):
  File "/home/erick/Documents/personal projects/gift a box/virtual/lib/python3.6/site-packages/cart/models.py", line 27, in Item
    cart = models.ForeignKey(Cart, verbose_name=_('cart'))
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by ansuman13** [comment]
Did you solve this ?

**Comment by kornikopic** [comment]
Since django 2+, you need to add on_delete for every foreignkey : https://docs.djangoproject.com/en/2.0/ref/models/fields/#foreignkey

**Comment by Anirudh-M-C** [comment]
problem with the definition of a ForeignKey field


code:
from django.db import models
from django.utils.translation import gettext_lazy as _

from .cart import Cart

class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('cart'), on_delete=models.CASCADE)
